services:
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: lab2
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 8702
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 5s
      retries: 5
      start_period: 10s

  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      DB_USERNAME: postgres
      DB_PASSWORD: 8702
      DB_NAME: lab2
      DB_HOST: db
      DB_PORT: 5432
      TESTING_APP_SECRET: dGVzdGluZ1NlY3JldEtleVRvTWFrZUl0TG9uZ2VyISE=
      TESTING_APP_LIFETIME: 600000
      MAIL_USERNAME: nurzanmirasov685@gmail.com
      MAIL_PASSWORD: ryvkzwozzmpdvrwu
    depends_on:
      db:
        condition: service_healthy

volumes:
  pgdata:
